services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-tecconn
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3336:3306'
    networks: 
      - tecconn-network
networks:
  tecconn-network:
    driver: bridge